# .travis.yml for R projects.
# See https://docs.travis-ci.com/user/languages/r/

language: r

# Enable if a more recent version of Ubuntu is helpful.
# This gives us g++-4.8, which is needed for C++11 (e.g. ranger package)
dist: trusty

# Disable sudo so that we can use container infrastructure and package caching.
sudo: false
# Enable sudo so that we can use apt-get to upgrade and install linux packages.
# We also need sudo for r_binary_packages listed below.
# sudo: required

r:
  # Test current version of R, dev version, and previous major verison.
  - release
  - devel
  - oldrel

# This only works if sudo = false.
cache: packages

os:
  - linux
  - osx

matrix:
  # Report build completion status once non-"allow_failures" builds are done.
  fast_finish: true
  # Allow failures on OSX.
  allow_failures:
    - os: osx

compiler:
  - gcc
  #- clang

env:
  global:
    #- R_BUILD_ARGS="--no-build-vignettes --no-manual"
    - R_CHECK_TIME="TRUE"
    - R_CHECK_TESTS="TRUE"
    # This does not appear to do anything.
    - MAKEFLAGS="-j 2"
    # No error if suggested packages are not available.
    #- _R_CHECK_FORCE_SUGGESTS_=0

cran: "http://cran.rstudio.com"
warnings_are_errors: true
#r_check_args: "--no-build-vignettes --no-manual --as-cran --timings"
r_check_args: "--as-cran --timings"
r_build_args:

# Override default Travis build process so that we can add conditional
# reverse dependency checking.
# Build and check lines based on travis docs:
# https://docs.travis-ci.com/user/languages/r/#Customizing-the-Travis-build-steps
script:
  # Install callr manually since CRAN version is old and this may help
  # tests/cran/revdep.R to work correctly.
  # Installing using r_github_packages doesn't seem to work right.
  - Rscript -e 'source("https://install-github.me/r-lib/callr")'
  - R CMD build . #--no-build-vignettes --no-manual
  - R CMD check *tar.gz --as-cran --timings
  - if [ "${SL_CRAN}" == "true" ]; then
      Rscript --verbose tests/cran/revdep.R;
    fi


r_packages:
# Install survival directly, to get the latest version and avoid
# a build error from using an older version.
  - survival

r_github_packages:
  - jimhester/covr
  # Use custom devtools that shows more info during revdep_check()
  - ck37/devtools
  #- jimhester/lintr

bioc_packages:
  - sva
  - genefilter

after_success:
  # Only check test coverage for R = release and OS = linux.
  - test ${TRAVIS_R_VERSION_STRING} == "release" && test ${TRAVIS_OS_NAME} == "linux" && Rscript -e 'covr::codecov()'

#after_failure:
  # This doesn't do anything because travis-tool.sh is no longer used.
  # - ./travis-tool.sh dump_logs
